using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PhxLib.HaloWars
{
	public enum BAnimType
	{
		Idle,
		Walk,
		Jog,
		Run,
		RangedAttack,
		Attack,
		Limber,
		Unlimber,
		Death,
		Work,
		Research,
		Train,
		Bored,
		PelicanGarrison,
		PelicanGarrison2,
		PelicanGarrison3,
		PelicanGarrison4,
		PelicanGarrison5,
		PelicanGarrison6,
		PelicanGarrison7,
		PelicanGarrison8,
		PelicanGarrison9,
		PelicanGarrison10,
		PelicanUngarrison,
		PelicanUngarrison2,
		PelicanUngarrison3,
		PelicanUngarrison4,
		PelicanUngarrison5,
		PelicanUngarrison6,
		PelicanUngarrison7,
		PelicanUngarrison8,
		PelicanUngarrison9,
		PelicanUngarrison10,
		Incoming,
		Landing,
		Takeoff,
		Outgoing,
		HoverIdle,
		ShadePlasmaAttack,
		Clamshell,
		ClamshellRocket,
		Cinematic,
		EvadeLeft,
		EvadeRight,
		EvadeFront,
		EvadeBack,
		Block,
		Cheer,
		Retreat,
		HandSignalGo,
		HandSignalStop,
		Reload,
		CombatAction,
		Flail,
		Stop,
		TurnAround,
		TurnLeft,
		TurnRight,
		TurnRight45Forward,
		TurnRight45Back,
		TurnLeft45Back,
		TurnLeft45Forward,
		TurnWalk,
		TurnJog,
		TurnRun,
		Repair,
		FloodDeathJog,
		FloodDeath,
		IdleWalk,
		IdleJog,
		IdleRun,
		WalkIdle,
		JogIdle,
		RunIdle,
		Hitch,
		Unhitch,
		Sprint,
		Recover,
		Heal,
		ArtilleryAttack,
		LockdownArtilleryAttack,
		Stasis,
		Roar,
		Cower,
		Kamikaze,
		Stunned,
		Detonated,
		ShatterDeath,
		RageLeap,
		HotDropDown,
		PowerIdle,
	};

	public enum BChatSpeaker
	{
		Serena,
		Forge,
		Cutter,
		Voice_of_God,
		Generic_Soldiers,
		Arcadian_Police,
		Civilians,
		Anders,
		RhinoCommander,
		Spartan1,
		Spartan2,
		SpartanSniper,
		SpartanRockeLauncher,

		Covenant = Anders,
		Arbiter = RhinoCommander,

		ODST = SpartanRockeLauncher+1+1 + 1,
	};

	public enum BHUDItem
	{
		Minimap,
		Resources,
		Time,
		PowerStatus,
		Units,
		DpadHelp,
		ButtonHelp,
		Reticle,
		Score,
		UnitStats,
		CircleMenuExtraInfo,
	};

	public enum BFlashableUIItem // aka FlashableItems
	{
		Minimap,
		CircleMenu0,
		CircleMenu1,
		CircleMenu2,
		CircleMenu3,
		CircleMenu4,
		CircleMenu5,
		CircleMenu6,
		CircleMenu7,
		CircleMenuPop,
		CircleMenuPower,
		CircleMenuSupply,
		Dpad,
		DpadUp,
		DpadDown,
		DpadLeft,
		DpadRight,
		ResourcePanel,
		ResourcePanelPop,
		ResourcePanelPower,
		ResourcePanelSupply,
	};
}